apiVersion: v1
kind: Secret
metadata:
  name: firecrawl-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  OPENAI_BASE_URL: ""
  MODEL_NAME: ""
  MODEL_EMBEDDING_NAME: ""
  OLLAMA_BASE_URL: ""
  SLACK_WEBHOOK_URL: ""
  BULL_AUTH_KEY: ""
  TEST_API_KEY: ""
  POSTHOG_API_KEY: ""
  POSTHOG_HOST: ""
  SUPABASE_ANON_TOKEN: ""
  SUPABASE_URL: ""
  SUPABASE_SERVICE_TOKEN: ""
  SCRAPING_BEE_API_KEY: ""
  SELF_HOSTED_WEBHOOK_URL: ""
  SERPER_API_KEY: ""
  SEARCHAPI_API_KEY: ""
  LOGGING_LEVEL: ""
  PROXY_SERVER: ""
  PROXY_USERNAME: ""
  PROXY_PASSWORD: ""
  SEARXNG_ENDPOINT: ""
  SEARXNG_ENGINES: ""
  SEARXNG_CATEGORIES: ""
  USE_DB_AUTHENTICATION: ""
  BLOCK_MEDIA: "" 