name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  API_IMAGE_NAME: docker4zerocool/firecrawl-api
  PLAYWRIGHT_IMAGE_NAME: docker4zerocool/firecrawl-playwright

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/api
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:latest

      - name: Build and push Playwright image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/playwright-service-ts
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.PLAYWRIGHT_IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.PLAYWRIGHT_IMAGE_NAME }}:latest

      - name: Update Kubernetes manifests
        if: github.ref == 'refs/heads/main'
        run: |
          sed -i "s|docker.io/docker4zerocool/firecrawl-api:latest|${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:${{ github.sha }}|g" k8s/base/deployment.yaml
          sed -i "s|docker.io/docker4zerocool/firecrawl-playwright:latest|${{ env.REGISTRY }}/${{ env.PLAYWRIGHT_IMAGE_NAME }}:${{ github.sha }}|g" k8s/base/deployment.yaml

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add k8s/base/deployment.yaml
          git commit -m "Update image tags to ${{ github.sha }}" || echo "No changes to commit"
          git push 